# Generated by Django 3.0.6 on 2020-06-08 14:07

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Published Date')),
                ('likes', models.IntegerField()),
                ('thumbnail', models.FileField(upload_to=article.models.get_upload_file_name)),
            ],
        ),
    ]
